#! /bin/sh
sxhkd &
$HOME/.config/polybar/launch.sh &
picom --experimental-backends &
numlockx on &
nitrogen --restore &
nm-applet &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# colors #
bspc config normal_border_color "#4E5165"
bspc config active_border_color "#599CAA"
bspc config focused_border_color "#7ae6f2"
bspc config presel_feedback_color "#6272a4"
# colors #

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
xsetroot -cursor_name left_ptr &

